version: '3'

services:
  drawbu_dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/drawbu:/pool/process
    environment:
      - GITHUB_PROFILE=drawbu
      - REPO_URL=https://github.com/drawbu/Notes
